/* This file is autogenerated, do not edit*/
#include "moc_double-slider.cpp"
#include "moc_auto-scene-switcher.cpp"
#include "moc_output-timer.cpp"
#include "moc_properties-view.cpp"
#include "moc_properties-view.moc.cpp"
#include "moc_vertical-scroll-area.cpp"
